apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsyncs.secrets.configsync.gke.io
spec:
  group: secrets.configsync.gke.io
  names:
    kind: SecretSync
    plural: secretsyncs
    singular: secretsync
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                secretRef:
                  type: string
                projectID:
                  type: string
