apiVersion: secrets.configsync.gke.io/v1beta1
kind: SecretSync
metadata:
  name: my-sample-secret
  namespace: default
spec:
  secretStore:
    provider: gcp
    gcp:
      projectID: july-do-not-delete
  remoteRef:
    name: my-sample-secret
